kind: pipeline
name: default

steps:
  - name: build
    image: node:10
    volumes:
      - name: target
        path: /drone/target/vioao.github.io
    commands:
      - npm install
      - ./node_modules/hexo/bin/hexo clean && ls
      - ./node_modules/hexo/bin/hexo g && ls
      - cat /drone/src/public/README.MD
      - cat ./themes/next/source/README.MD
      - rm -rf /drone/target/vioao.github.io/* && cp -r ./public/* /drone/target/vioao.github.io/
      - pwd && ls
      - ls /drone/src/public
      - cat /drone/src/public/README.MD
    when:
      branch:
        - blog

  - name: publish github pages
    image: vioao/drone-gh-pages
    settings:
      remote_url: https://github.com/vioao/vioao.github.io.git
      pages_directory: ./public/
      target_branch: master
      username:
        from_secret: github_username
      password:
        from_secret: github_password

volumes:
  - name: target
    host:
      path: /var/www/vioao.github.io
