kind: pipeline
name: default

steps:
  - name: build
    image: node
    volumes:
      - name: target
        path: /drone/target/vioao.github.io
    commands:
      - npm install
      - ./node_modules/hexo/bin/hexo clean
      - ./node_modules/hexo/bin/hexo g
      - rm -rf /drone/target/vioao.github.io/*
      - cp -r /drone/src/public/* /drone/target/vioao.github.io
      - mkdir github_pages && cp -r /drone/src/public/* /drone/src/github_pages
      - mkdir coding_pages && cp -r /drone/src/public/* /drone/src/coding_pages
    when:
      branch:
        - blog

  - name: publish github pages
    image: plugins/gh-pages
    settings:
      remote_url: https://github.com/vioao/vioao.github.io.git
      pages_directory: github_pages
      target_branch: master
      temporary_base: .github_tmp
      username:
        from_secret: github_username
      password:
        from_secret: github_password

  - name: publish coding pages
    image: vioao/drone-gh-pages
    settings:
      machine: git.coding.net
      remote_url: https://git.coding.net/vioao/vioao.git
      pages_directory: coding_pages
      target_branch: master
      temporary_base: .coding_tmp
      username:
        from_secret: coding_username
      password:
        from_secret: coding_password

volumes:
  - name: target
    host:
      path: /var/www/mine
