kind: pipeline
name: default

steps:
  - name: build
    image: node
    volumes:
      - name: target
        path: /drone/src/github.com/vioao/vioao.github.io/public
    commands:
      - pwd
      - npm install
      - ./node_modules/hexo/bin/hexo clean
      - ./node_modules/hexo/bin/hexo g
    when:
      branch:
        - blog

volumes:
  - name: target
    host:
      path: /var/www/mine